import = ["~/.config/alacritty/keybindings.toml"]

[font]
  normal = { family = "MesloLGS NF", style = "Regular" }
  size = 9.0

[colors.primary]
  background = "#000000"

[cursor.style]
  shape = "Beam"

[env]
  term = "xterm-256color"

