[general]
import = [
  "~/.config/alacritty/keybindings.toml",
  # "~/.config/alacritty/themes/themes/gruvbox_light.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_material_medium_light.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
  # "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
  # "~/.config/alacritty/themes/themes/iterm.toml"
  # "~/.config/alacritty/themes/themes/tokyo_night_storm.toml"
  # "~/.config/alacritty/themes/themes/dracula.toml"
  # "~/.config/alacritty/themes/themes/github_dark.toml"
  "~/.config/alacritty/themes/themes/solarized_osaka.toml"
]

[font]
  normal = { family = "MesloLGS NF", style = "Regular" }
  size = 9.0

# [colors.primary]
#   background = "#000000"

[cursor.style]
  shape = "Underline"

[env]
  term = "xterm-256color"

